name: Build and Deploy Blog

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:     # Manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser beautifulsoup4

      - name: Run blog build script
        run: python build_script.py

      - name: Commit and push any changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Update blog posts"
          git push
